const axios = require("axios");

/**
 * Sends dynamic reference/passcode via WhatsApp Cloud API
 * @param {string} recipientPhone - Recipient phone with country code (e.g. "919876543210")
 * @param {string|number} otpCode - The verification code generated by your app
 */
async function sendWhatsAppOtp(recipientPhone, otpCode) {
  const phoneNumberId = process.env.WHATSAPP_PHONE_NUMBER_ID;
  const token = process.env.WHATSAPP_TOKEN;

  // Clean phone number: remove '+' and any non-numeric characters
  const cleanPhone = String(recipientPhone).replace(/\D/g, "");

  const payload = {
    messaging_product: "whatsapp",
    recipient_type: "individual",
    to: cleanPhone,
    type: "template",
    template: {
      name:
        process.env.WHATSAPP_TEMPLATE_NAME ||
        "YOUR_EXACT_APPROVED_TEMPLATE_NAME",
      language: {
        code: "en",
      },
      components: [
        {
          type: "body",
          parameters: [
            {
              type: "text",
              text: String(otpCode),
            },
          ],
        },
      ],
    },
  };

  const response = await axios.post(
    `https://graph.facebook.com/v20.0/${phoneNumberId}/messages`,
    payload,
    {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
    },
  );

  return response.data;
}

module.exports = { sendWhatsAppOtp };
